-- PostgreSQL / Supabase schema. Idempotent: cleandb.bat reapplies it for alignment, and DB_AUTO_SETUP can install it on a fresh database. It never resets portfolio content.

BEGIN;

CREATE SCHEMA IF NOT EXISTS portfolio;

REVOKE ALL ON SCHEMA portfolio FROM PUBLIC;

SET LOCAL search_path = portfolio, public;

CREATE TABLE IF NOT EXISTS access_requests (
            id TEXT PRIMARY KEY,
            browser_secret_hash TEXT NOT NULL,
            grant_token_hash TEXT NOT NULL UNIQUE,
            otp_hash TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','granted','completed','failed','expired')),
            wrong_attempts INTEGER NOT NULL DEFAULT 0,
            ip_address TEXT NOT NULL,
            fingerprint_hash TEXT NOT NULL,
            device_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMPTZ NOT NULL,
            granted_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS admin_sessions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            token_hash TEXT NOT NULL UNIQUE,
            fingerprint_hash TEXT,
            ip_address TEXT,
            user_agent TEXT,
            expires_at TIMESTAMPTZ NOT NULL,
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS certificates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            image_blob BYTEA,
            image_mime TEXT NOT NULL,
            storage_path TEXT NOT NULL DEFAULT '',
            storage_url TEXT NOT NULL DEFAULT '',
            source_url TEXT NOT NULL DEFAULT '',
            certificate_date TEXT NOT NULL,
            provider TEXT NOT NULL,
            visible INTEGER NOT NULL DEFAULT 1 CHECK(visible IN (0,1)),
            pinned INTEGER NOT NULL DEFAULT 0 CHECK(pinned IN (0,1)),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS contact_auth_sessions (
            token_hash TEXT PRIMARY KEY,
            provider TEXT NOT NULL DEFAULT 'google' CHECK(provider='google'),
            provider_user_id TEXT NOT NULL,
            display_name TEXT NOT NULL,
            email TEXT NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        , profile_url TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS contact_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name TEXT NOT NULL,
            email TEXT NOT NULL,
            subject TEXT NOT NULL,
            message TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','read','archived')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        , profile_url TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS feedback (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            display_name TEXT NOT NULL,
            rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
            comment TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','hidden')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        , pinned INTEGER NOT NULL DEFAULT 0, auth_provider TEXT NOT NULL DEFAULT 'legacy', auth_user_id TEXT NOT NULL DEFAULT '', credential TEXT NOT NULL DEFAULT '', profile_url TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS feedback_auth_sessions (
            token_hash TEXT PRIMARY KEY,
            provider TEXT NOT NULL CHECK(provider IN ('google','github','facebook','telegram')),
            provider_user_id TEXT NOT NULL,
            display_name TEXT NOT NULL,
            credential TEXT NOT NULL DEFAULT '',
            profile_url TEXT NOT NULL DEFAULT '',
            expires_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS page_visits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            visitor_hash TEXT NOT NULL,
            path TEXT NOT NULL DEFAULT '/',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE INDEX IF NOT EXISTS idx_access_requests_fingerprint_created ON access_requests(fingerprint_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_access_requests_ip_created ON access_requests(ip_address, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_access_requests_status_expires ON access_requests(status, expires_at);

CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires ON admin_sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_certificates_provider ON certificates(provider);

CREATE INDEX IF NOT EXISTS idx_certificates_public ON certificates(visible, pinned DESC, certificate_date DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contact_auth_expires ON contact_auth_sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_contact_status_created ON contact_messages(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_feedback_auth_expires ON feedback_auth_sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_feedback_public ON feedback(status, pinned DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_feedback_status_created ON feedback(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_page_visits_created ON page_visits(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_page_visits_visitor_created ON page_visits(visitor_hash, created_at DESC);



CREATE TABLE IF NOT EXISTS career_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type TEXT NOT NULL CHECK(document_type IN ('resume','cv','biodata')),
    title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 160),
    description TEXT NOT NULL DEFAULT '' CHECK(length(description)<=2000),
    storage_path TEXT NOT NULL,
    storage_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0 CHECK(file_size>=0),
    visible SMALLINT NOT NULL DEFAULT 1 CHECK(visible IN (0,1)),
    display_order INTEGER NOT NULL DEFAULT 1 CHECK(display_order>0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_career_profiles_public ON career_profiles(visible,display_order,updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_threads (
    id TEXT PRIMARY KEY,
    visitor_token_hash TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','closed')),
    admin_unread INTEGER NOT NULL DEFAULT 0 CHECK(admin_unread>=0),
    visitor_unread INTEGER NOT NULL DEFAULT 0 CHECK(visitor_unread>=0),
    visitor_ip TEXT NOT NULL DEFAULT '',
    visitor_ip_hash TEXT NOT NULL DEFAULT '',
    visitor_user_agent TEXT NOT NULL DEFAULT '',
    visitor_agent TEXT NOT NULL DEFAULT '',
    visitor_platform TEXT NOT NULL DEFAULT '',
    visitor_country TEXT NOT NULL DEFAULT '',
    visitor_referrer TEXT NOT NULL DEFAULT '',
    visitor_fingerprint TEXT NOT NULL DEFAULT '',
    visitor_auth_provider TEXT NOT NULL DEFAULT '',
    visitor_auth_name TEXT NOT NULL DEFAULT '',
    visitor_auth_credential TEXT NOT NULL DEFAULT '',
    visitor_profile_url TEXT NOT NULL DEFAULT '',
    last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- Additive P7 chat metadata migration. These fields use only server-observable
-- request data plus an already-authorized OAuth identity; no canvas/audio
-- fingerprinting is performed. Chat threads and metadata share the 7-day lifecycle.
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_ip TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_ip_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_user_agent TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_agent TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_platform TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_country TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_referrer TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_fingerprint TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_auth_provider TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_auth_name TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_auth_credential TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_threads ADD COLUMN IF NOT EXISTS visitor_profile_url TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_chat_threads_recent ON chat_threads(last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_threads_ip_hash ON chat_threads(visitor_ip_hash) WHERE visitor_ip_hash<>'';
CREATE INDEX IF NOT EXISTS idx_chat_threads_fingerprint ON chat_threads(visitor_fingerprint) WHERE visitor_fingerprint<>'';

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id TEXT NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
    sender TEXT NOT NULL CHECK(sender IN ('visitor','admin')),
    body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days')
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_thread ON chat_messages(thread_id,created_at,id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_expiry ON chat_messages(expires_at);

CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, installed_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO schema_version(version) VALUES (4) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS sync_state (
    id INTEGER PRIMARY KEY CHECK (id=1), revision BIGINT NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO sync_state(id) VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS personal_information (
    id INTEGER PRIMARY KEY CHECK (id=1), content JSONB NOT NULL CHECK (jsonb_typeof(content)='object'),
    version BIGINT NOT NULL DEFAULT 1, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 160),
    description TEXT NOT NULL DEFAULT '' CHECK (length(description)<=20000),
    url TEXT NOT NULL DEFAULT '', source_url TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL DEFAULT 'Project', icon TEXT NOT NULL DEFAULT '',
    technologies_json JSONB NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(technologies_json)='array'),
    images_json JSONB NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(images_json)='array'),
    visible SMALLINT NOT NULL DEFAULT 1 CHECK (visible IN (0,1)),
    display_order INTEGER NOT NULL DEFAULT 1 CHECK (display_order>0),
    status TEXT NOT NULL DEFAULT 'unknown' CHECK (status IN ('online','offline','unknown')),
    checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_projects_order ON projects(display_order,created_at,id);

-- Storage migration compatibility. Existing P4 databases started with BYTEA media.
-- P5 moves images to Supabase Storage and leaves BYTEA nullable only as a safe
-- migration fallback until cleandb.bat uploads the legacy rows.
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS storage_path TEXT NOT NULL DEFAULT '';
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS storage_url TEXT NOT NULL DEFAULT '';
ALTER TABLE certificates ALTER COLUMN image_blob DROP NOT NULL;
CREATE TABLE IF NOT EXISTS project_media (
    id TEXT PRIMARY KEY, image_blob BYTEA CHECK (image_blob IS NULL OR octet_length(image_blob)<=5242880),
    image_mime TEXT NOT NULL CHECK (image_mime IN ('image/png','image/jpeg','image/webp','image/gif')),
    storage_path TEXT NOT NULL DEFAULT '',
    storage_url TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE project_media ADD COLUMN IF NOT EXISTS storage_path TEXT NOT NULL DEFAULT '';
ALTER TABLE project_media ADD COLUMN IF NOT EXISTS storage_url TEXT NOT NULL DEFAULT '';
ALTER TABLE project_media ALTER COLUMN image_blob DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_certificates_storage_path ON certificates(storage_path) WHERE storage_path<>'';
CREATE INDEX IF NOT EXISTS idx_project_media_storage_path ON project_media(storage_path) WHERE storage_path<>'';

CREATE OR REPLACE FUNCTION portfolio.touch_public_revision() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path=portfolio,pg_temp AS $$
BEGIN
    UPDATE portfolio.sync_state SET revision=revision+1,updated_at=clock_timestamp() WHERE id=1;
    RETURN NULL;
END; $$;
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['personal_information','projects','certificates','feedback','career_profiles'] LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='public_revision_'||t
                       AND tgrelid=('portfolio.'||t)::regclass) THEN
            EXECUTE format('CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON portfolio.%I FOR EACH STATEMENT EXECUTE FUNCTION portfolio.touch_public_revision()', 'public_revision_'||t,t);
        END IF;
    END LOOP;
END; $$;
-- This private schema is intentionally NOT exposed through the Supabase Data API.
-- Only the trusted Go backend connects; do not add portfolio to exposed API schemas.
REVOKE ALL ON ALL TABLES IN SCHEMA portfolio FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA portfolio FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA portfolio FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA portfolio REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA portfolio REVOKE ALL ON SEQUENCES FROM PUBLIC;
COMMIT;
