import {$,openModal,closeModal,escapeHTML} from "./helpers.js";
let items=[];
function label(t){return t==="cv"?"Curriculum Vitae":t==="biodata"?"Biodata":"Resume"}
function render(){const grid=$("#careerAdminGrid");if(!grid)return;if(!items.length){grid.innerHTML='<div class="admin-empty">No Career Profile documents yet.</div>';return}grid.innerHTML=items.map(x=>`<article class="career-admin-card" data-id="${x.id}"><header><div><small>${escapeHTML(label(x.document_type))}</small><h3>${escapeHTML(x.title)}</h3></div><span class="status-pill ${x.visible?'approved':'hidden'}">${x.visible?'Published':'Hidden'}</span></header><p>${escapeHTML(x.description||'No description.')}</p><small>${escapeHTML(x.file_name)} · ${Math.max(1,Math.round((x.file_size||0)/1024))} KB · Order ${x.display_order}</small><div class="career-admin-actions"><a href="${escapeHTML(x.storage_url)}" target="_blank" rel="noopener">Preview</a><button type="button" data-edit> Edit</button><button class="danger" type="button" data-delete>Delete</button></div></article>`).join("");grid.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>edit(b.closest("[data-id]").dataset.id)));grid.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>remove(b.closest("[data-id]").dataset.id)))}
export async function loadCareer(){const data=await window.APIManager.getAdminCareerProfiles();items=data.items||[];render()}
function reset(){$("#careerForm").reset();$("#careerId").value="";$("#careerOrder").value="1";$("#careerVisible").checked=true;$("#careerModalTitle").textContent="Add document"}
function edit(id){const x=items.find(v=>String(v.id)===String(id));if(!x)return;reset();$("#careerId").value=x.id;$("#careerType").value=x.document_type;$("#careerTitle").value=x.title;$("#careerDescription").value=x.description||"";$("#careerOrder").value=x.display_order||1;$("#careerVisible").checked=!!x.visible;$("#careerModalTitle").textContent="Edit document";openModal("careerModal")}
async function remove(id){if(!confirm("Delete this Career Profile document? The PDF will also be removed from Supabase Storage."))return;try{await window.APIManager.deleteAdminCareerProfile(id);window.UI.toast("Document deleted.",{title:"Career Profile"});await loadCareer();await window.PublicStore.refresh({broadcast:true})}catch(e){window.UI.toast(e.message,{title:"Career Profile",type:"error"})}}
export function initCareer(){$("#addCareerButton")?.addEventListener("click",()=>{reset();openModal("careerModal")});$("#careerForm")?.addEventListener("submit",async e=>{e.preventDefault();const button=$("#saveCareerButton");const id=$("#careerId").value;const file=$("#careerFile").files?.[0];if(!id&&!file){window.UI.toast("Choose a PDF document.",{title:"Career Profile",type:"error"});return}const form=new FormData();form.append("document_type",$("#careerType").value);form.append("title",$("#careerTitle").value.trim());form.append("description",$("#careerDescription").value.trim());form.append("display_order",$("#careerOrder").value);form.append("visible",String($("#careerVisible").checked));if(file)form.append("file",file);window.UI.setButtonLoading(button,true,"Saving…");try{if(id)await window.APIManager.updateAdminCareerProfile(id,form);else await window.APIManager.addAdminCareerProfile(form);closeModal("careerModal");window.UI.toast(id?"Document updated.":"Document added.",{title:"Career Profile"});await loadCareer();await window.PublicStore.refresh({broadcast:true})}catch(err){window.UI.toast(err.message,{title:"Career Profile",type:"error"})}finally{window.UI.setButtonLoading(button,false)}})}
